# Generated by Django 3.1 on 2020-11-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quant',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
