# Generated by Django 3.1 on 2020-11-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201106_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='some',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
