# Generated by Django 3.1 on 2020-11-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201107_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unique_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
