# Generated by Django 3.1 on 2020-11-12 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='unique_id',
        ),
    ]
