# Generated by Django 3.1 on 2020-11-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_profile_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dflt_adrs_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
