# Generated by Django 3.1 on 2020-11-14 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_profileother'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dflt_adrs_id',
        ),
    ]
