# Generated by Django 3.1 on 2020-11-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20201120_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filters',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'SHIRT'), ('SW', 'SPORTWARE'), ('OW', 'OUTWARE'), ('EC', 'ELECTRONICS'), ('HA', 'HOMEAPPLIANCES'), ('FW', 'FOOTWARE')], max_length=2),
        ),
    ]
