# Generated by Django 3.1 on 2020-11-21 16:56

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20201120_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileother',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
    ]
